# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import proto_out.category_pb2 as category__pb2


class CategoriesServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getCategories = channel.unary_stream(
        '/CategoriesService/getCategories',
        request_serializer=category__pb2.GetCategoriesParams.SerializeToString,
        response_deserializer=category__pb2.Category.FromString,
        )


class CategoriesServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getCategories(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CategoriesServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getCategories': grpc.unary_stream_rpc_method_handler(
          servicer.getCategories,
          request_deserializer=category__pb2.GetCategoriesParams.FromString,
          response_serializer=category__pb2.Category.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'CategoriesService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
