# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: category.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='category.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0e\x63\x61tegory.proto\"\x15\n\x13GetCategoriesParams\":\n\x08\x43\x61tegory\x12\x0c\n\x04name\x18\x01 \x01(\t\x12 \n\rsubcategories\x18\x02 \x03(\x0b\x32\t.Category2I\n\x11\x43\x61tegoriesService\x12\x34\n\rgetCategories\x12\x14.GetCategoriesParams\x1a\t.Category\"\x00\x30\x01\x62\x06proto3'
)




_GETCATEGORIESPARAMS = _descriptor.Descriptor(
  name='GetCategoriesParams',
  full_name='GetCategoriesParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=39,
)


_CATEGORY = _descriptor.Descriptor(
  name='Category',
  full_name='Category',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Category.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subcategories', full_name='Category.subcategories', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=99,
)

_CATEGORY.fields_by_name['subcategories'].message_type = _CATEGORY
DESCRIPTOR.message_types_by_name['GetCategoriesParams'] = _GETCATEGORIESPARAMS
DESCRIPTOR.message_types_by_name['Category'] = _CATEGORY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetCategoriesParams = _reflection.GeneratedProtocolMessageType('GetCategoriesParams', (_message.Message,), {
  'DESCRIPTOR' : _GETCATEGORIESPARAMS,
  '__module__' : 'category_pb2'
  # @@protoc_insertion_point(class_scope:GetCategoriesParams)
  })
_sym_db.RegisterMessage(GetCategoriesParams)

Category = _reflection.GeneratedProtocolMessageType('Category', (_message.Message,), {
  'DESCRIPTOR' : _CATEGORY,
  '__module__' : 'category_pb2'
  # @@protoc_insertion_point(class_scope:Category)
  })
_sym_db.RegisterMessage(Category)



_CATEGORIESSERVICE = _descriptor.ServiceDescriptor(
  name='CategoriesService',
  full_name='CategoriesService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=101,
  serialized_end=174,
  methods=[
  _descriptor.MethodDescriptor(
    name='getCategories',
    full_name='CategoriesService.getCategories',
    index=0,
    containing_service=None,
    input_type=_GETCATEGORIESPARAMS,
    output_type=_CATEGORY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CATEGORIESSERVICE)

DESCRIPTOR.services_by_name['CategoriesService'] = _CATEGORIESSERVICE

# @@protoc_insertion_point(module_scope)
